### ISSUE TITLE
NettyChannelPool当多个获取连接超时后会导致服务不可用

### ISSUE THREAD

**Issue by jinyue233** [junxworks/junx#2]
public Channel acquire(int timeoutMillis) throws Exception {
		try {
			Future<Channel> fch = fixpool.acquire();
			// 这里连续n个获取连接超时后，因为没有归还连接，会造成连接池可用连接耗尽，最终导致服务不可用。注：n为连接池的数量
			// 解决方案：需要实现AcquireTimeoutAction的NEW或FAIL策略，因为您实现的代码创建FixedChannelPool连接池时AcquireTimeoutAction参数传的是null
			// Channel ch = fch.get(timeoutMillis, TimeUnit.MILLISECONDS);
			// 因为需要用到AcquireTimeoutAction策略，因此这里不需要超时了
			Channel ch = fch.get();
			return ch;
		} catch (Exception e) {
			logger.error("Exception accurred when acquire channel from channel pool.", e);
			throw e;
		}
	}

**Comment by junxworks** [comment]
非常感谢您的反馈，NettyChannelPoolManager对AcquireTimeoutAction和acquireTimeoutMillis的默认值，确实会带来这个问题，这个问题会在1.0.9版本进行修复，AcquireTimeoutAction默认是FAIL，acquireTimeoutMillis默认10秒，同时对io.github.junxworks.junx.netty.pool.NettyChannelPool.acquire(int timeoutMillis)方法做了重载，新版本迁移至https://gitee.com/junxworks/junx
